version: "3.8"
services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 8080:8080
    environment:
     - HelloMessage='Hello iac!'

  nginx:
    image: nginx:1.24
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 80:80
